### ISSUE TITLE
ERROR - common.h missing

### ISSUE THREAD

**Issue by ReefWarrior3D** [polhenarejos/pico-hsm#20]
Hi,

I have tried numerous times not to 'make' but I get the following:

[ 25%] Building C object CMakeFiles/pico_hsm.dir/src/hsm/sc_hsm.c.obj
In file included from /home/tinus/pico-hsm/src/hsm/sc_hsm.c:18:
/home/tinus/pico-hsm/src/hsm/sc_hsm.h:22:10: fatal error: common.h: No such file or directory
 #include "common.h"
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pico_hsm.dir/build.make:82: CMakeFiles/pico_hsm.dir/src/hsm/sc_hsm.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1767: CMakeFiles/pico_hsm.dir/all] Error 2
make: *** [Makefile:103: all] Error 

PLEASE HELP! :) 
Tinus

**Comment by polhenarejos** [comment]
Which branch? Which commit? Try with the latest of `development`.
