### ISSUE TITLE
Support for YD-RP2040 by VCC-GND Studio ?

### ISSUE THREAD

**Issue by rexackermann** [polhenarejos/pico-hsm#29]
I was wondering if this board is supported ?
It's [YD-RP2040](http://152.32.187.208:8080/yd-data/YD-RP2040/) 16MB version.

**Comment by polhenarejos** [comment]
It should be but not out of the box.

If your board does not appear at Pico SDK [https://github.com/raspberrypi/pico-sdk/tree/master/src/boards/include/boards], a board header file must be created (see other boards for an example).  Then, using `PICO_BOARD` parameter in `cmake` should use that header.

**Comment by rexackermann** [comment]
Okay, apparently no support for now.
Thanks for the reply.
