### ISSUE TITLE
Press-to-confirm button

### ISSUE THREAD

**Issue by fastchain** [polhenarejos/pico-hsm#39]
Hello!

Thank you for the great project!

According to this description 

https://github.com/polhenarejos/pico-hsm/blob/98e9b72b42a128d5cc2bd74dedb742a59662ccc0/doc/extra_command.md#press-to-confirm-button

It seems the press-to-confirm function can be enabled and disabled without requiring any authentication. This raises a concern that malware could potentially disable it without notice, rendering the press-to-confirm control ineffective. Is it possible lock this setting to prevent such actions?

**Comment by fastchain** [comment]
Hello,

Here is the fix https://github.com/polhenarejos/pico-hsm/pull/40

**Comment by polhenarejos** [comment]
Merged.
