### ISSUE TITLE
Missing  pypicohsm

### ISSUE THREAD

**Issue by lboschiazzo** [polhenarejos/pico-hsm#46]
When runing pico-hsm-tool.py for pico-hsm initialization, it complains that pypicohsm is missing. But running `pip install pypicohsm` pip doesn´t find the module, there is not such module.

Reproduction steps:
- Clone the repo
- run pip install pycvc
- run pico-hsm-tool.py from tools dir.
- get the error
- run pip install pypicohsm
- get 'ERROR: No matching distribution found for pypicohsm'

Thanks in advance!

**Comment by polhenarejos** [comment]
You can find it at https://github.com/polhenarejos/pypicohsm

I’ll push the packet to pypi soon.

**Comment by lboschiazzo** [comment]
Thank you very much!

Excellent work, btw!
