### ISSUE TITLE
Pico-HSM serial number

### ISSUE THREAD

**Issue by lboschiazzo** [polhenarejos/pico-hsm#56]
It is possible to individualize each pico-hsm with a different Serial Number?

Thanks!

**Comment by polhenarejos** [comment]
SN is at MCU level. RP2040 does not provide a true unique SN whilst RP2350 does. There’s a device_id get from QSPI XIP but it’s not guaranteed to be unique.

**Comment by lboschiazzo** [comment]
Ok, it's a hardware constraint.

Thank you very much!
