### ISSUE TITLE
Commissioning failed: pico/pico-hsm/cvc Error 500

### ISSUE THREAD

**Issue by rrottmann** [polhenarejos/pico-hsm#63]
ESP32S3 freshly flashed cannot be commisioned. Web console shows communication hence and forth to the Pico Key with last line Public Point: 04dff...36e

POST https://www.picokeys.com/pico/pico-ham/cvc yields error 500 in wcid.js?v10:42

SyntaXError: Unexpected token '<', "<!DOCTYPE " is not valid JSON

![Screenshot_2024-11-22_16-44-12](https://github.com/user-attachments/assets/7b02a045-fb53-49a2-a047-5c4a020dfa58)

**Comment by polhenarejos** [comment]
Perhaps is a temporary problem with the backend. Can you try again?

**Comment by polhenarejos** [comment]
A bug in the frontend affecting only ESP32.

If you refresh the page F5 should be fixed. If not, try deleting the cache.

**Comment by polhenarejos** [comment]
Please paste line 142 of wcid.js

**Comment by rrottmann** [comment]
[wcid.js](https://www.picokeys.com/js/wcid.js?v10)

```140   const pbk = base64UrlEncode(Y);
141   let params = { pubkey: pbk }
142   if (platform == PICO_PLATFORM.RP2350) {
143       params.curve = 'secp256k1';
144   }
```

**Comment by polhenarejos** [comment]
Ok, you are using the unpatched js, probably due to some cache. I've updated the versioning so you should see the corrected one.

**Comment by rrottmann** [comment]
Works like a charm now.
